server {
    listen 3000;
    server_name localhost;

    root /home/tamim/Documents/cloud/d2/assignment/app/frontend;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
